# ----
# Site

title: BAO - Better Authentication Online
description: BAO API documentation.
#url: https://developers.baosec.com   # with the https protocol
#enforce_ssl: developers.baosec.com   # without any protocol
google_analytics_key: UA-92808648-1
permalink: pretty

collections:
  documentation:
    title: Documentation
    position: 1
  u2fapi:
    title: U2F API
    position: 2
  uafapi:
    title: UAF API
    position: 3
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
